export type Product = {
  id: number;
  name: string;
  price: string;
  priceValue: number;
  image: string;
  category: string;
  description: string;
  fabric: string;
  weight: string;
  care: string;
  tag?: string;
  sizes: string[];
  colors: string[];
  occasions: string[];
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Aura Flare Dress",
    price: "KSH 1,800",
    priceValue: 1800,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop",
    category: "Weekend Casual",
    description: "The essence of femininity. A flowing flare dress with a cinched waist.",
    fabric: "Premium Crepe",
    weight: "Lightweight",
    care: "Gentle wash.",
    tag: "Best Seller",
    sizes: ["S", "M", "L"],
    colors: ["Pink", "White"],
    occasions: ["Casual", "Day Out"]
  },
  {
    id: 2,
    name: "Midnight Flare Jumpsuit",
    price: "KSH 2,000",
    priceValue: 2000,
    image: "https://images.unsplash.com/photo-1539109132382-361a57053099?q=80&w=1000&auto=format&fit=crop",
    category: "Office Dresses",
    description: "Wide-leg elegance for the modern powerhouse.",
    fabric: "Premium Spandex",
    weight: "Medium",
    care: "Dry clean.",
    tag: "Trending",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Blue"],
    occasions: ["Office", "Dinner"]
  },
  {
    id: 3,
    name: "Siren Sexy Dress",
    price: "KSH 1,500",
    priceValue: 1500,
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop",
    category: "Date Night",
    description: "Designed to turn heads. Figure-hugging and bold.",
    fabric: "Stretch Satin",
    weight: "Light",
    care: "Hand wash.",
    sizes: ["S", "M"],
    colors: ["Red", "Black"],
    occasions: ["Date Night", "Dinner"]
  },
  {
    id: 4,
    name: "Divine Maxy Dress",
    price: "KSH 1,950",
    priceValue: 1950,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop",
    category: "Church Fits",
    description: "Floor-length glamour for a queenly presence.",
    fabric: "Georgette Silk",
    weight: "Light",
    care: "Steam iron.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Gold"],
    occasions: ["Wedding", "Church"]
  },
  {
    id: 5,
    name: "Gala Birthday Dress",
    price: "KSH 1,850",
    priceValue: 1850,
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
    category: "Birthday Dresses",
    description: "Shine on your special day with this exquisite piece.",
    fabric: "Tulle & Lace",
    weight: "Medium",
    care: "Dry clean.",
    tag: "Birthday",
    sizes: ["S", "M", "L"],
    colors: ["Gold", "Pink"],
    occasions: ["Birthday", "Gala"]
  },
  {
    id: 6,
    name: "Royal Lace Dress",
    price: "KSH 1,700",
    priceValue: 1700,
    image: "https://images.unsplash.com/photo-1523359346063-d8793b4bd007?q=80&w=1000&auto=format&fit=crop",
    category: "Event Looks",
    description: "Intricate lace patterns for a sophisticated look.",
    fabric: "French Lace",
    weight: "Light",
    care: "Delicate wash.",
    sizes: ["M", "L"],
    colors: ["White", "Blue"],
    occasions: ["Wedding", "Brunch"]
  },
  {
    id: 7,
    name: "Silk Satin Slip",
    price: "KSH 1,600",
    priceValue: 1600,
    image: "https://images.unsplash.com/photo-1518767761162-d5335a54c66d?q=80&w=1000&auto=format&fit=crop",
    category: "Dinner Dresses",
    description: "Smooth as silk. Perfect for effortless elegance.",
    fabric: "Luxury Satin",
    weight: "Very Light",
    care: "Hand wash.",
    sizes: ["S", "M", "L"],
    colors: ["Emerald", "Silver"],
    occasions: ["Casual", "Dinner"]
  },
  {
    id: 8,
    name: "Duo Skirt Set",
    price: "KSH 1,900",
    priceValue: 1900,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
    category: "Weekend Casual",
    description: "A matching 2-piece set for the fashion-forward.",
    fabric: "Ribbed Knit",
    weight: "Medium",
    care: "Machine wash.",
    sizes: ["S", "M", "L"],
    colors: ["Orange", "Grey"],
    occasions: ["Office", "Casual"]
  },
  {
    id: 9,
    name: "Cloud Balloon Dress",
    price: "KSH 1,750",
    priceValue: 1750,
    image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?q=80&w=1000&auto=format&fit=crop",
    category: "Weekend Casual",
    description: "Voluminous sleeves and a playful silhouette.",
    fabric: "Organic Cotton",
    weight: "Medium",
    care: "Iron low.",
    sizes: ["S", "M", "L"],
    colors: ["Yellow", "Pink"],
    occasions: ["Casual", "Day Out"]
  },
  {
    id: 10,
    name: "Vixen Bareback Dress",
    price: "KSH 2,000",
    priceValue: 2000,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop",
    category: "Date Night",
    description: "Breathtaking back design that speaks volumes.",
    fabric: "Lycra Silk",
    weight: "Light",
    care: "Hand wash.",
    tag: "New Arrival",
    sizes: ["S", "M"],
    colors: ["Black", "Gold"],
    occasions: ["Dinner", "Date Night"]
  },
  {
    id: 11,
    name: "Soiree Dinner Dress",
    price: "KSH 1,800",
    priceValue: 1800,
    image: "https://images.unsplash.com/photo-1523359346063-d8793b4bd007?q=80&w=1000&auto=format&fit=crop",
    category: "Dinner Dresses",
    description: "Elegance served for your evening plans.",
    fabric: "Chiffon",
    weight: "Light",
    care: "Delicate dry.",
    tag: "New Arrival",
    sizes: ["M", "L", "XL"],
    colors: ["Emerald", "Silver"],
    occasions: ["Dinner", "Gala"]
  },
  {
    id: 12,
    name: "Boss 2-Piece Trouser",
    price: "KSH 2,000",
    priceValue: 2000,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop",
    category: "Office Dresses",
    description: "Command the room with this tailored trouser set.",
    fabric: "Linen Blend",
    weight: "Structured",
    care: "Dry clean.",
    tag: "New Arrival",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "White"],
    occasions: ["Office", "Professional"]
  },
  {
    id: 13,
    name: "Petal Mini Tote",
    price: "KSH 1,650",
    priceValue: 1650,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
    category: "Mini Bags",
    description: "Compact elegance for your essentials. Hand-stitched with premium vegan leather.",
    fabric: "Vegan Leather",
    weight: "Very Light",
    care: "Wipe with damp cloth.",
    tag: "New Arrival",
    sizes: ["OS"],
    colors: ["Pink", "Tan"],
    occasions: ["Casual", "Day Out"]
  },
  {
    id: 14,
    name: "Empress Satchel",
    price: "KSH 1,900",
    priceValue: 1900,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1000&auto=format&fit=crop",
    category: "Office Bags",
    description: "A statement piece for the boardroom and beyond. Timeless structured design.",
    fabric: "Embossed Leather",
    weight: "Medium",
    care: "Store in dust bag.",
    sizes: ["OS"],
    colors: ["Black", "Brown"],
    occasions: ["Office", "Formal"]
  },
  {
    id: 15,
    name: "Gilded Evening Clutch",
    price: "KSH 1,550",
    priceValue: 1550,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fd15dadc?q=80&w=1000&auto=format&fit=crop",
    category: "Party Bags",
    description: "The perfect companion for your dinner dresses. Features champagne gold accents.",
    fabric: "Satin & Gold Hardware",
    weight: "Light",
    care: "Handle with care.",
    tag: "Evening Essential",
    sizes: ["OS"],
    colors: ["Gold", "Silver"],
    occasions: ["Dinner", "Wedding"]
  },
  {
    id: 16,
    name: "Crystal Luxury Heels",
    price: "KSH 3,200",
    priceValue: 3200,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop",
    category: "Luxury Heels",
    description: "Towering elegance with crystal embellishments. For the queen who walks with grace.",
    fabric: "Silk Satin & Crystals",
    weight: "Light",
    care: "Clean with soft brush.",
    tag: "Luxury",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Silver", "Gold"],
    occasions: ["Wedding", "Gala"]
  },
  {
    id: 17,
    name: "Urban Chic Sneakers",
    price: "KSH 2,500",
    priceValue: 2500,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop",
    category: "Sneakers",
    description: "Comfort meets high fashion. Perfect for your off-duty model looks.",
    fabric: "Breathable Mesh & Leather",
    weight: "Medium",
    care: "Machine washable.",
    sizes: ["37", "38", "39", "40", "41"],
    colors: ["White", "Pink"],
    occasions: ["Casual", "Day Out"]
  },
  {
    id: 18,
    name: "Classic Noir Heels",
    price: "KSH 2,800",
    priceValue: 2800,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop",
    category: "Heels",
    description: "The essential black stiletto every power house woman needs.",
    fabric: "Premium Suede",
    weight: "Medium",
    care: "Wipe clean.",
    sizes: ["37", "38", "39", "40"],
    colors: ["Black"],
    occasions: ["Office", "Dinner"]
  },
  {
    id: 19,
    name: "Lady Boss Handbag",
    price: "KSH 3,500",
    priceValue: 3500,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
    category: "Handbags",
    description: "Large capacity meets luxury design. Carry your empire in style.",
    fabric: "Top Grain Leather",
    weight: "Heavy",
    care: "Condition regularly.",
    sizes: ["OS"],
    colors: ["Black", "Nude"],
    occasions: ["Office", "Professional"]
  }
];
